name: Trigger CircleCI Build

on:
  push:
    branches:
      - master

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Build
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl -u ${CIRCLECI_TOKEN}: \
          -d build_parameters[CIRCLE_JOB]=build \
          https://circleci.com/api/v1.1/project/github/MKODALI7/flutter_ui_challenge_flight_search/tree/master
